pub mod auth;
pub mod diagnostics;
pub mod error;
pub mod input;
pub mod ipmi;
pub mod media;
pub mod playback;
pub mod power;
pub mod preferences;
pub mod protocol;
pub mod recording;
pub mod recordings;
pub mod recovery;
pub mod server;
pub mod service;
pub mod sharing;
pub mod transport;
pub mod video;

pub use error::{Error, Result};
pub const VERSION: &str = env!("CARGO_PKG_VERSION");
